language: python

python:
  - 3.5

sudo: false

env:
  - TOX_ENV=py27-flake8
  - TOX_ENV=precommit

matrix:
  fast_finish: true

install:
  - pip install virtualenv tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
